In [22]:
import tensorflow as tf

sequence_features = {'pos': tf.io.RaggedFeature(tf.int64), 
                     'artist_name':  tf.io.RaggedFeature(tf.string), 
                     'track_uri':  tf.io.RaggedFeature(tf.string), 
                     'artist_uri': tf.io.RaggedFeature(tf.string), 
                     'track_name': tf.io.RaggedFeature(tf.string), 
                     'album_uri': tf.io.RaggedFeature(tf.string),
                     'duration_ms': tf.io.RaggedFeature(tf.int64), 
                     'album_name': tf.io.RaggedFeature(tf.string)
                    }
context_features = {"pl_name" : tf.io.FixedLenFeature(dtype=tf.string, shape=(1)),
                    "collaborative" : tf.io.FixedLenFeature(dtype=tf.string, shape=(1)),
                    "modified_at_playlist" : tf.io.FixedLenFeature(dtype=tf.int64, shape=(1)),
                    "num_tracks" : tf.io.FixedLenFeature(dtype=tf.int64, shape=(1)),
                    "num_albums" : tf.io.FixedLenFeature(dtype=tf.int64, shape=(1)),
                    "num_followers" :tf.io.FixedLenFeature(dtype=tf.int64, shape=(1)),
                    "num_edits" :tf.io.FixedLenFeature(dtype=tf.int64, shape=(1)),
                    "duration_ms" : tf.io.FixedLenFeature(dtype=tf.int64, shape=(1)),
                    "num_artists" : tf.io.FixedLenFeature(dtype=tf.int64, shape=(1)),
                    "description" : tf.io.FixedLenFeature(dtype=tf.string, shape=(1)),
                    "genres" : tf.io.FixedLenFeature(dtype=tf.string, shape=(1)),
                    "time_signature" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "uri" : tf.io.FixedLenFeature(dtype=tf.string, shape=(1)),
                    "tempo" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "valence" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "liveness" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "instrumentalness" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "acousticness" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "speechiness" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "mode" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "loudness" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "key" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "energy" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "danceability" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "speechiness" : tf.io.FixedLenFeature(dtype=tf.float32, shape=(1)),
                    "artist_name" : tf.io.FixedLenFeature(dtype=tf.string, shape=(1)),
                    "track_name" : tf.io.FixedLenFeature(dtype=tf.string, shape=(1)),
                    "album_name" : tf.io.FixedLenFeature(dtype=tf.string, shape=(1))    
                   }

def parse_tfrecord_fn(example):
    example = tf.io.parse_single_sequence_example(example, sequence_features=sequence_features, context_features=context_features)
    return example

In [29]:
from pprint import pprint
raw_dataset = tf.data.TFRecordDataset("gs://spotify-tfrecords/2022-04-25:13:30:01.339691/file_15000-1.tfrec")

tf_record_pipeline = raw_dataset.map(parse_tfrecord_fn)

for _ in tf_record_pipeline.batch(10).take(1):
    pprint(_)

({'acousticness': <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[7.28e-04],
       [1.57e-01],
       [9.90e-01],
       [4.57e-04],
       [1.36e-02],
       [1.57e-01],
       [7.42e-01],
       [1.57e-01],
       [6.36e-01],
       [7.42e-01]], dtype=float32)>,
  'album_name': <tf.Tensor: shape=(10, 1), dtype=string, numpy=
array([[b'Tourist History'],
       [b'Exis'],
       [b'Comfort and Joy'],
       [b'Saint Cecilia EP'],
       [b'Youth Revival'],
       [b'Exis'],
       [b'Alvin & The Chipmunks / OST'],
       [b'Exis'],
       [b'Youth Revival'],
       [b'Alvin & The Chipmunks / OST']], dtype=object)>,
  'artist_name': <tf.Tensor: shape=(10, 1), dtype=string, numpy=
array([[b'Two Door Cinema Club'],
       [b'Roy Woods'],
       [b'Becky and Ernie Brock'],
       [b'Foo Fighters'],
       [b'Hillsong Young & Free'],
       [b'Roy Woods'],
       [b'Alvin & The Chipmunks'],
       [b'Roy Woods'],
       [b'Hillsong Young & Free'],
       [b'Alvin & The Chipmunks'